### ISSUE TITLE
Requester name spills into project name when to long, maybe add...

### ISSUE THREAD

**Issue by christake** [VicAv99/venturplex-helpq#7]
```css
.truncate {
  width: 250px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
```
